### ISSUE TITLE
Problem with sass when using 'make'.

### ISSUE THREAD

**Issue by romanglom** [programmfabrik/easydb-ubhd-3d-viewer-plugin#2]
I'm having a problem when using the command 'make', I get this error:

```
cat src/webfrontend/easydb-ubhd-3d-viewer-plugin.scss | sass --scss --no-cache --sourcemap=inline > build/webfrontend/easydb-ubhd-3d-viewer-plugin.css
make: *** [Makefile:63: build/webfrontend/easydb-ubhd-3d-viewer-plugin.css] Error 64
```

If I open the css generated, I see the output of the command sass.

```
Could not find an option named "scss".

Usage: sass <input.scss> [output.css]
       sass <input.scss>:<output.css> <input/>:<output/> <dir/>
```

My sass version is **1.35.2 compiled with dart2js 2.13.4**

I could make it work if I modify the Makefile like this, but I don't want to modify it, since you are probably using a different version.
```
$(CSS): $(SCSS_FILES)
        mkdir -p $(dir $@)
        sass $(SCSS_FILES) $(CSS)
```

What version of sass are you using? Thanks.

**Comment by lmaylein** [comment]
We use
Sass 3.4.23 (Selective Steve)
which comes together with Ubuntu 18.04
If I understand it correctly, the `--scss` option is needed there to handle SCSS correctly.
At the moment, however, the scss file contains pure css. But this could change in the future.
Does your sass version automatically distinguish between scss and sass format?

**Comment by romanglom** [comment]
Oh, you are using the old version of sass, the one that used Ruby. That version is deprecated https://sass-lang.com/ruby-sass

My suggestion is you to upgrade the version to the last one, the one compiled with dart: https://github.com/sass/dart-sass

Is it ok for you to change the version? If you do that, you will have to also change the Makefile. If you want to keep the version you are using, I would have to do something in the Makefile so it supports both sass versions, but I wouldn't recommend it.

**Comment by lmaylein** [comment]
Yes, we can change the version. But wouldn't it be better to change this line:

`call_scss = sass --scss --no-cache --sourcemap=inline`

**Comment by romanglom** [comment]
Well, yes. It would be "easier" to modify the Makefile so it works for both, as long as both libraries use the same cli parameters.

The problem is that the dart version does not have the "--scss, --no-cache, --sourcemap" parameters, and you need to use the parameter --stdin the get the same result (https://sass-lang.com/documentation/cli/dart-sass)

For example, this solution works for the dart version, but probably it won't in the ruby version.

```
call_scss = sass

$(CSS): $(SCSS_FILES)
        mkdir -p $(dir $@)
        cat $(SCSS_FILES) | $(call_scss) --stdin > $(CSS)

```

Besides, I highly suggest to use the new version.

**Comment by lmaylein** [comment]
My suggestion would be:

```
call_scss = sass --stdin

$(CSS): $(SCSS_FILES)
        mkdir -p $(dir $@)
        cat $(SCSS_FILES) | $(call_scss) > $(CSS)
```

That should work with both versions, at least as long as scss is not really used.

**Comment by lmaylein** [comment]
@romanglom : Would you agree to this fix?

**Comment by romanglom** [comment]
I'm sorry for the late reply, I was on holiday.

In your suggestion you just moved ```--stdin```, so it keeps working with the version I have, but would it work for the version you use?

I'm not sure what you mean with 'as long as scss is not really used'

**Comment by lmaylein** [comment]
I was just about to see how this is solved in other plugins, e.g. here: 
https://github.com/programmfabrik/easydb-custom-data-type-html-editor/blob/main/Makefile
https://github.com/programmfabrik/easydb-example-plugin/blob/master/Makefile

Where is the "css" defined there that is referenced here?
`build: code css npm_install updater buildinfojson`

> I'm not sure what you mean with 'as long as scss is not really used'

I use a pure CSS file here, which actually does not need to be translated at all but only copied.

**Comment by romanglom** [comment]
You do have a SCSS file set in your Makefile. If you don't use it, you can remove that line and the file, so we won't have any problem with the sass versions because we won't use it.

`SCSS_FILES = src/webfrontend/easydb-ubhd-3d-viewer-plugin.scss`

The `css` is defined in the easydb-library Makefile: base-plugins.make 

```
css: $(CSS)

$(CSS): $(SCSS_FILES)
	mkdir -p $(dir $@)
	cat $(SCSS_FILES) | $(WEBFRONTEND_SASS) --stdin > $(CSS) || ( rm -f $(CSS) ; false )
```

It is included in each plugin like this: `include easydb-library/tools/base-plugins.make`


You overrode the $(CSS) in your Makefile, but you are using SCSS_FILES anyways:
```
$(CSS): $(SCSS_FILES)
        mkdir -p $(dir $@)
        cat $(SCSS_FILES) | $(call_scss) > $(CSS)
```

**Comment by lmaylein** [comment]
I have switched to the default method in easydb-library.
Could you please test?

**Comment by romanglom** [comment]
The last change is good for us, it works. Thanks!
